# Description: Containerfile for ogp-panel

# We have to have got php-7.x & apache2 installed (derive from debian:11-slim)
FROM php:7.4-apache

# Image metadata as described above
LABEL org.opencontainers.image.authors="Mickael Patron"
LABEL org.opencontainers.image.source="https://github.com/DiacreOrg/images"
LABEL org.opencontainers.image.path="ogp-panel/Containerfile"
LABEL org.opencontainers.image.title="ogp-panel"
LABEL org.opencontainers.image.description="A php based image for ogp-panel"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.url="https://opengamepanel.org/install_guide/panel.html"
LABEL org.opencontainers.image.vendor="DiacreOrg"
LABEL org.opencontainers.image.created="2025-05-08T00:00:00Z"
LABEL org.opencontainers.image.revision="1.0.0"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.documentation="https://github.com/DiacreOrg/images/readme.md"

# VARIABLES TEMPORAIRES
ARG APT_FLAGS="--quiet --assume-yes --no-install-recommends"
ARG DOCUMENT_ROOT="/var/www/html"
ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBIAN_PRIORITY="critical"

# RÉPERTOIRE DE TRAVAIL
WORKDIR /app

# INSTALLATION D'APACHE
# INSTALLATION DES LIBRAIRIES NÉCESSAIRES
RUN apt-get update ${APT_FLAGS} \
    && apt-get install ${APT_FLAGS} \
         git \
         libxml2-dev \
         zlib1g-dev \
         libzip-dev \
    && apt-get autoclean ${APT_FLAGS} \
    && rm -rf /var/lib/apt

RUN git clone https://github.com/OpenGamePanel/OGP-Website.git . \
    && chown -R www-data:www-data .

# CONFIGURATION DU SERVEUR APACHE
ADD vhost.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# CONFIGURATION DU SITE PHP
ADD config.inc.php /app/includes/
RUN docker-php-ext-install \
    bcmath \
    mysqli \
    xmlrpc \
    zip

# OUVERTURE DU PORT HTTP
# Déjà fait dans l'image de base
# EXPOSE 80

# DÉMARRAGE DES SERVICES LORS DE L'EXÉCUTION DE L'IMAGE
# Déjà fait dans l'image de base
# ENTRYPOINT apache2ctl -D FOREGROUND
# ENTRYPOINT service apache2 start